const commd = require("../commd")
const outputs = require("../outputs")
const equals = require('./equals')
const tsjq_zogl = require("../tsjq-zogl")
tsjq_zogl(commd, outputs, equals)
    .then(wlyc => wlyc.isOk() ? console.log(wlyc) : console.log(wlyc.getErr())).catch(err => { console.error(err) })