const yf = require('../yf.json')
const dsyf = require('../dsyf.json')
const ytm_yf = {
    nou: "nu",
    mou: "mu",
    kou: "ku",
    fiu: "fu",
    giu: "gu",
    hiu: "hu",
    deu: "dju",
    beu: "bu",
    vau: "vju",
    // wau: "wu",
    yau: "yu",
    lou: "lu",
}
const lr_zt_rjyf = {
    wj: "oʤ",
    hh: "hʌn",
    lu: 'lu'
}
const eysj_yhti_rjyf = {
    lu: 'lu',
    // sn: 'sn', sn fl gkdb oc sn[ktdbsz] yh(13 n eysj), yndf zbhm qqgq ym ac kk.
    sh: 'shi',
    // sl: "slo", cd zqjp db uuld cgne pj lq ja s zqjp vo s yfm, gq acdb bi yhti xbyb pj.
    // sp: "spu", cd zqjp db uuld cgne pj lq ja s zqjp vo s yfm, gq acdb bi yhti xbyb pj.
    // st: "stu", cd zqjp db uuld cgne pj lq ja s zqjp vo s yfm, gq acdb bi yhti xbyb pj.
}
const eysj_nomr_rjyf = {
    // no: "nəʊ",
    // mo: "məʊ",
    // to: "təʊ",
    // so: "səʊ",
    // ro: "rəʊ",
    // po: "pəʊ",
    // lo: "ləʊ",
    // vo: "vəʊ",
    // yo: "yəʊ",
    // bo: "bəʊ",
    do: "du",
    // fo: "fəʊ",
    // go: "gəʊ",
    // ho: "həʊ",
    // jo: "jəʊ",
    zo: "zo",
    la: "la",
    na: "na",
    ma: "ma",
    ta: "ta",
    sa: "sa",
    ra: "ra",
    pa: "pa",
    ba: "ba",
    da: "da",
    ja: "ʤa",
    ga: "ga",
    ha: "ha",
    ni: "ni",
    mi: "mi",
    ti: "ti",
    si: "si",
    pi: "pi",
    li: "li",
    bi: "bi",
    ki: "ki",
    vi: "vi",
    wi: "wi",
    yi: "yi",
    zi: "zi",
    ji: "ʤi"

}
const eysj_ll_yf = {
    wy: 'wai',
    py: "pai",
    tu: "tju",
    tr: "tru",
    pr: "pru",
    qr: "kru",
    xr: "kra",
    cr: "kri",
    dr: "dre",
    br: "bre",
    fr: "fri",
    gr: "gri",
    jr: "ʤro",
    kr: "kro",
    // ts: "tis'",
    // ds: "dis'",
    // ks: "kis'",
    // ps: "pis'",
    // bs: "bis'",
    // fs: "fis'",
    // hs: "his'",
    // js: "ʤis'",
    // ls: "lis'",
    // ms: "mis'",
    // ns: "nis'",
    // rs: "ris'",
    // us: "jus'",
    // vs: "vis'",
    // ws: "wis'",
    // zs: "zis'",
    // gs: "gis'",
    th: "θu",
    sh: "ʃi",
    ry: 'rai',
    ly: 'lai'
}
const ll_ae_ds_n_ztka = {
    py: 'pai',
    ty: 'tai',
    dy: 'dai',
    by: 'bai',
    fy: 'fai',
    gy: 'gai',
    hy: 'hai',
    jy: 'ʤai',
    ky: 'kai',
    my: 'mai',
    ny: 'nai',
    vy: 'vai',
    // zk: 'zik'
}
const eysj_ds_rjyf = {
    kt: 'kt',
    bt: 'bt',
    st: 'st',
    pt: 'pt',
    ps: 'ps',
    zk: 'zik',
    zd: "zid",
    zt: "zit",
    sh: "shi",
    th: "θ",
    dm: "dәm",
    sm: "sәm",
    lm: "lʌm",
    km: "kәm",
    mm: "mʌm",
    nm: "nʌm",
    fm: "fom",
    // bm: "bʌm",
    gm: "gʌm",
    jm: "ʤʌm",
    pm: "pʌm",
    tm: "tʌm",
    ph: "pʌn",
    wm: "wɜm",
}
module.exports = {
    eysj_ds_rjyf,
    eysj_ll_yf,
    eysj_nomr_rjyf,
    ll_ae_ds_n_ztka,
    ytm_yf,
    yf,
    eysj_yhti_rjyf,
    lr_zt_rjyf,
    dsyf
}