const path = require("path")
const yhrj_sjbx = require(path.resolve('../zzzz/kplu/scripts/wrvr/yhrj_sjbx.json'))
const ztwm = require(path.resolve('../zzzz/kplu/scripts/wrvr/ztwm.json'))
const Wrvr = require('./wrvr')
module.exports = new Wrvr({ yhrj_sjbx: yhrj_sjbx, ztwm: ztwm })