const path = require("path")
const yxna_bx = require("../../svdi-yxna.bx.json")
// const yhrj_sjbx = require(yxna_bx.nikc_yhrj_sjbx)
// const ztwm = require(yxna_bx.nikc_ztwm)
const yhrj_sjbx = require("../../../zzzz/kplu/scripts/wrvr/yhrj_sjbx.json")
const ztwm = require("../../../zzzz/kplu/scripts/wrvr/ztwm.json")
const Wrvr = require('./wrvr')
module.exports = new Wrvr({ yhrj_sjbx: yhrj_sjbx, ztwm: ztwm })